defmodule Geometry.PolygonZ do
  # This file is auto-generated by `mix geometry.gen`.
  # The ZM version of this file is used as a template.

  @moduledoc """
  A polygon struct, representing a 3D polygon.

  A none empty line-string requires at least one ring with four points.
  """

  use Geometry.Protocols

  alias Geometry.LineStringZ
  alias Geometry.PolygonZ

  defstruct rings: []

  @type t :: %PolygonZ{rings: [Geometry.coordinates()]}

  @doc """
  Creates an empty `PolygonZ`.

  ## Examples

      iex> PolygonZ.new()
      %PolygonZ{rings: []}
  """
  @spec new :: t()
  def new, do: %PolygonZ{}

  @doc """
  Creates a `PolygonZ` from the given `rings`.

  ## Examples

      iex> PolygonZ.new([
      ...>   LineStringZ.new([
      ...>     PointZ.new(35, 10, 13),
      ...>     PointZ.new(45, 45, 23),
      ...>     PointZ.new(10, 20, 33),
      ...>     PointZ.new(35, 10, 13)
      ...>   ]),
      ...>   LineStringZ.new([
      ...>     PointZ.new(20, 30, 13),
      ...>     PointZ.new(35, 35, 23),
      ...>     PointZ.new(30, 20, 33),
      ...>     PointZ.new(20, 30, 13)
      ...>   ])
      ...> ])
      %PolygonZ{
        rings: [
          [[35, 10, 13], [45, 45, 23], [10, 20, 33], [35, 10, 13]],
          [[20, 30, 13], [35, 35, 23], [30, 20, 33], [20, 30, 13]]
        ]
      }

      iex> PolygonZ.new()
      %PolygonZ{}
  """
  @spec new([LineStringZ.t()]) :: t()
  def new(rings) when is_list(rings) do
    %PolygonZ{rings: Enum.map(rings, fn line_string -> line_string.points end)}
  end
end
