defmodule Geometry.LineStringTest do
  # This file is auto-generated by `mix geometry.gen`.
  # The ZM version of this file is used as a template.

  use ExUnit.Case

  import Prove

  alias Geometry.{LineString, Point}

  doctest Geometry.LineString, import: true

  @moduletag :line_string

  describe "new/0:" do
    prove LineString.new() == %LineString{points: []}
  end

  describe "new/1:" do
    @line_string %LineString{
      points: [%Point{x: 1, y: 1}, %Point{x: 2, y: 2}]
    }

    prove LineString.new([Point.new(1, 1), Point.new(2, 2)]) == @line_string
    prove LineString.new([]) == %LineString{points: []}
    prove LineString.new() == %LineString{points: []}
  end

  describe "new/1" do
    test "raises an error for an invalid list" do
      assert_raise FunctionClauseError, fn ->
        LineString.new([Point.new(1, 1)])
      end
    end
  end

  describe "from_coordinates/1:" do
    @line_string %LineString{
      points: [%Point{x: 1, y: 1}, %Point{x: 2, y: 2}]
    }

    prove LineString.from_coordinates([{1, 1}, {2, 2}]) == @line_string
  end

  describe "to_wkt/2:" do
    @line_string LineString.new([
                   Point.new(1.1, 1.2),
                   Point.new(2.1, 2.2),
                   Point.new(3.1, 3.2)
                 ])

    prove LineString.to_wkt(@line_string) ==
            "LineString (1.1 1.2, 2.1 2.2, 3.1 3.2)"

    prove LineString.to_wkt(@line_string, srid: 678) ==
            "SRID=678;LineString (1.1 1.2, 2.1 2.2, 3.1 3.2)"

    prove LineString.to_wkt(LineString.new()) == "LineString EMPTY"
  end

  describe "from_wkt/1:" do
    prove LineString.from_wkt("LineString empty") == {:ok, %LineString{}}

    prove LineString.from_wkt("LineString (5 4, 3.1 -44.5)") ==
            {:ok,
             %LineString{
               points: [
                 %Point{x: 5, y: 4},
                 %Point{x: 3.1, y: -44.5}
               ]
             }}

    prove LineString.from_wkt("srid=77;LineString (1.1 -2.2, 5 7)") ==
            {:ok,
             %LineString{
               points: [
                 %Point{x: 1.1, y: -2.2},
                 %Point{x: 5, y: 7}
               ]
             }, 77}

    prove LineString.from_wkt("Point (5 6)") ==
            {:error, %{expected: LineString, got: Point}}

    prove LineString.from_wkt("SRID=55;Point (4 5)") ==
            {:error, %{expected: LineString, got: Point}}

    prove LineString.from_wkt("linestring XY (5 6)") ==
            {:error, "expected LineString data", "XY (5 6)", {1, 0}, 11}
  end

  describe "from_wkt!/1:" do
    prove LineString.from_wkt!("LineString (5 4, 3.1 -44.5)") ==
            %LineString{
              points: [
                %Point{x: 5, y: 4},
                %Point{x: 3.1, y: -44.5}
              ]
            }

    prove LineString.from_wkt!("srid=77;LineString (1.1 -2.2, 5 7)") ==
            {%LineString{
               points: [
                 %Point{x: 1.1, y: -2.2},
                 %Point{x: 5, y: 7}
               ]
             }, 77}

    test "raises an exception" do
      message = "expected 'SRID', 'Geometry' or 'SRID;Geometry' at 1:0, got: 'foo'"

      assert_raise Geometry.Error, message, fn ->
        LineString.from_wkt!("foo")
      end
    end
  end

  describe "empty?/:" do
    prove LineString.empty?(LineString.new()) == true

    prove LineString.empty?(LineString.from_coordinates([{1, 2}, {3, 4}])) ==
            false
  end

  describe "from_geo_json/1:" do
    prove LineString.from_geo_json(%{}) == {:error, :type_not_found}
  end

  describe "from_geo_json/1" do
    test "with valid data" do
      geo_json =
        Jason.decode!("""
        {
          "type": "LineString",
          "coordinates": [[1, 2],[3, 4]]
        }
        """)

      assert GeoJsonValidator.valid?(geo_json)

      assert LineString.from_geo_json(geo_json) ==
               {:ok,
                %LineString{
                  points: [%Point{x: 1, y: 2}, %Point{x: 3, y: 4}]
                }}
    end

    test "with invalid data" do
      geo_json =
        Jason.decode!("""
        {
          "type": "LineString",
          "coordinates": [[1, 2], [3, 4, 5]]
        }
        """)

      assert LineString.from_geo_json(geo_json) == {:error, :invalid_data}
    end
  end

  describe "from_geo_json!/1" do
    test "with valid data" do
      geo_json =
        Jason.decode!("""
        {
          "type": "LineString",
          "coordinates": [[1, 2],[3, 4]]
        }
        """)

      assert GeoJsonValidator.valid?(geo_json)

      assert LineString.from_geo_json!(geo_json) ==
               %LineString{
                 points: [%Point{x: 1, y: 2}, %Point{x: 3, y: 4}]
               }
    end

    test "raises an exception" do
      geo_json = %{"type" => "foo"}
      message = "type not found"

      assert_raise Geometry.Error, message, fn ->
        LineString.from_geo_json!(geo_json)
      end
    end
  end

  describe "to_geo_json/1" do
    @line_string %LineString{
      points: [%Point{x: 1, y: 2}, %Point{x: 3, y: 4}]
    }

    prove LineString.to_geo_json(@line_string) == %{
            "coordinates" => [[1, 2], [3, 4]],
            "type" => "LineString"
          }

    prove @line_string |> LineString.to_geo_json() |> GeoJsonValidator.valid?() == true
  end

  describe "from_wkb/1" do
    test "returns an ok tuple with LineString" do
      wkb = """
      01\
      02000000\
      02000000\
      9A9999999999F1BF9A999999999901C0\
      00000000000016406666666666661A40\
      """

      assert LineString.from_wkb(wkb) ==
               {:ok,
                %LineString{
                  points: [
                    %Point{x: -1.1, y: -2.2},
                    %Point{x: 5.5, y: 6.6}
                  ]
                }}
    end

    test "returns an ok tuple with LineString and SRID" do
      wkb = """
      00\
      20000002\
      0000004D\
      00000002\
      BFF199999999999AC00199999999999A\
      4016000000000000401A666666666666\
      """

      assert LineString.from_wkb(wkb) ==
               {:ok,
                %LineString{
                  points: [
                    %Point{x: -1.1, y: -2.2},
                    %Point{x: 5.5, y: 6.6}
                  ]
                }, 77}
    end
  end

  describe "from_wkb!/1" do
    test "returns a LineString" do
      wkb = """
      01\
      02000000\
      02000000\
      9A9999999999F1BF9A999999999901C0\
      00000000000016406666666666661A40\
      """

      assert LineString.from_wkb!(wkb) ==
               %LineString{
                 points: [
                   %Point{x: -1.1, y: -2.2},
                   %Point{x: 5.5, y: 6.6}
                 ]
               }
    end

    test "returns a LineString and SRID" do
      wkb = """
      00\
      20000002\
      0000004D\
      00000002\
      BFF199999999999AC00199999999999A\
      4016000000000000401A666666666666\
      """

      assert LineString.from_wkb!(wkb) ==
               {
                 %LineString{
                   points: [
                     %Point{x: -1.1, y: -2.2},
                     %Point{x: 5.5, y: 6.6}
                   ]
                 },
                 77
               }
    end

    test "raises an exception" do
      message = "expected endian flag '00' or '01', got 'AB', at position 0"

      assert_raise Geometry.Error, message, fn ->
        LineString.from_wkb!("ABCDEFGH")
      end
    end
  end

  describe "to_wkb/2" do
    test "returns WKB from LineString" do
      wkb = """
      01\
      02000000\
      02000000\
      9A9999999999F1BF9A999999999901C0\
      00000000000016406666666666661A40\
      """

      assert LineString.to_wkb(%LineString{
               points: [
                 %Point{x: -1.1, y: -2.2},
                 %Point{x: 5.5, y: 6.6}
               ]
             }) == wkb
    end

    test "returns WKB from LineString with SRID" do
      wkb = """
      00\
      20000002\
      0000004D\
      00000002\
      BFF199999999999AC00199999999999A\
      4016000000000000401A666666666666\
      """

      assert LineString.to_wkb(
               %LineString{
                 points: [
                   %Point{x: -1.1, y: -2.2},
                   %Point{x: 5.5, y: 6.6}
                 ]
               },
               endian: :xdr,
               srid: 77
             ) == wkb
    end
  end
end
