defmodule Geometry.MultiLineStringMTest do
  # This file is auto-generated by `mix geometry.gen`.
  # The ZM version of this file is used as a template.

  use ExUnit.Case, async: true

  alias Geometry.{Hex, LineStringM, MultiLineStringM, PointM}

  doctest Geometry.MultiLineStringM, import: true

  @moduletag :multi_line_string

  describe "to_geo_json/1" do
    test "returns geo-json-term" do
      geo_json =
        MultiLineStringM.to_geo_json(
          MultiLineStringM.from_coordinates([
            [[-1, 1, 1], [2, 2, 2], [-3, 3, 3]],
            [[-10, 10, 10], [-20, 20, 20]]
          ])
        )

      assert GeoJsonValidator.valid?(geo_json)

      assert geo_json |> Map.keys() |> Enum.sort() == ["coordinates", "type"]
      assert Map.get(geo_json, "type") == "MultiLineString"

      assert geo_json |> Map.get("coordinates") |> Enum.sort() == [
               [[-10, 10, 10], [-20, 20, 20]],
               [[-1, 1, 1], [2, 2, 2], [-3, 3, 3]]
             ]
    end
  end

  describe "from_geo_json!/2" do
    test "returns a MultiLineStringM" do
      geo_json =
        Jason.decode!("""
           {
             "type": "MultiLineString",
             "coordinates": [
               [[-1, 1, 1], [2, 2, 2], [-3, 3, 3]],
               [[-10, 10, 10], [-20, 20, 20]]
             ]
           }
        """)

      multi_line_string =
        MultiLineStringM.new([
          LineStringM.new([
            PointM.new(-1, 1, 1),
            PointM.new(2, 2, 2),
            PointM.new(-3, 3, 3)
          ]),
          LineStringM.new([
            PointM.new(-10, 10, 10),
            PointM.new(-20, 20, 20)
          ])
        ])

      assert MultiLineStringM.from_geo_json!(geo_json) == multi_line_string
    end

    test "raises an error for an invalid geo-json-term" do
      message = "type not found"

      assert_raise Geometry.Error, message, fn ->
        MultiLineStringM.from_geo_json!(%{})
      end
    end
  end

  describe "to_wkt/2" do
    test "returns WKT for an empty MultiLineStriingZM" do
      assert MultiLineStringM.to_wkt(MultiLineStringM.new()) ==
               "MultiLineString M EMPTY"
    end

    test "returns WKT for a MultiLineStringM" do
      wkt =
        MultiLineStringM.to_wkt(
          MultiLineStringM.new([
            LineStringM.new([PointM.new(7.1, 8.1, 1), PointM.new(9.2, 5.2, 2)]),
            LineStringM.new([PointM.new(5.5, 9.2, 1), PointM.new(1.2, 3.2, 2)])
          ])
        )

      assert String.starts_with?(wkt, "MultiLineString M")
      assert wkt =~ "(5.5 9.2 1, 1.2 3.2 2)"
      assert wkt =~ "(7.1 8.1 1, 9.2 5.2 2)"
    end

    test "returns WKT with SRID for a MultiLineStringM" do
      wkt =
        MultiLineStringM.to_wkt(
          MultiLineStringM.new([
            LineStringM.new([PointM.new(7.1, 8.1, 1), PointM.new(9.2, 5.2, 2)]),
            LineStringM.new([PointM.new(5.5, 9.2, 1), PointM.new(1.2, 3.2, 2)])
          ]),
          srid: 555
        )

      assert String.starts_with?(wkt, "SRID=555;MultiLineString M")
      assert wkt =~ "(5.5 9.2 1, 1.2 3.2 2)"
      assert wkt =~ "(7.1 8.1 1, 9.2 5.2 2)"
    end
  end

  describe "from_wkt!/1" do
    test "returns a LineStringM" do
      wkt = """
      MultiLineString M (
        (10 20 45, 20 10 15, 20 40 15),
        (40 30 20, 30 30 30)
      )
      """

      multi_line_string = %MultiLineStringM{
        line_strings:
          MapSet.new([
            [
              [40, 30, 20],
              [30, 30, 30]
            ],
            [
              [10, 20, 45],
              [20, 10, 15],
              [20, 40, 15]
            ]
          ])
      }

      assert MultiLineStringM.from_wkt!(wkt) == multi_line_string
    end

    test "returns a LineStringM with SRID" do
      wkt = """
      SRID=1234;MultiLineString M (
        (10 20 45, 20 10 15, 20 40 15),
        (40 30 20, 30 30 30)
      )
      """

      multi_line_string = %MultiLineStringM{
        line_strings:
          MapSet.new([
            [
              [40, 30, 20],
              [30, 30, 30]
            ],
            [
              [10, 20, 45],
              [20, 10, 15],
              [20, 40, 15]
            ]
          ])
      }

      assert MultiLineStringM.from_wkt!(wkt) == {multi_line_string, 1234}
    end

    test "raises an error for an invalid WKT" do
      message = ~s(expected 'SRID', 'Geometry' or 'SRID;Geometry' at 1:0, got: "Larry")

      assert_raise Geometry.Error, message, fn ->
        MultiLineStringM.from_wkt!("Larry")
      end
    end
  end

  describe "to_wkb/2" do
    test "returns WKB as xdr-binary from a MultiLineStringM" do
      wkb_start = "0040000005000000020040000002"

      multi_line_string = %MultiLineStringM{
        line_strings:
          MapSet.new([
            [
              [40.0, 40.0, 20.0],
              [30.0, 30.0, 50.0]
            ],
            [
              [10.0, 10.0, 30.0],
              [20.0, 20.0, 50.0],
              [10.0, 40.0, 20.0]
            ]
          ])
      }

      # Because the order is not guaranteed we test here this way.

      assert result = MultiLineStringM.to_wkb(multi_line_string, endian: :xdr)
      assert String.starts_with?(result, Hex.to_binary(wkb_start))
      assert MultiLineStringM.from_wkb!(result) == multi_line_string
    end

    test "returns WKB as xdr-string from a MultiLineStringM" do
      wkb_start = "0040000005000000020040000002"

      multi_line_string = %MultiLineStringM{
        line_strings:
          MapSet.new([
            [
              [40.0, 40.0, 20.0],
              [30.0, 30.0, 50.0]
            ],
            [
              [10.0, 10.0, 30.0],
              [20.0, 20.0, 50.0],
              [10.0, 40.0, 20.0]
            ]
          ])
      }

      # Because the order is not guaranteed we test here this way.

      assert result = MultiLineStringM.to_wkb(multi_line_string, endian: :xdr, mode: :hex)
      assert String.starts_with?(result, wkb_start)
      assert MultiLineStringM.from_wkb!(result, :hex) == multi_line_string
    end
  end

  describe "from_wkb/2" do
    test "returns a MultiLineStringM from xdr-string" do
      wkb = """
      00\
      40000005\
      00000002\
      00\
      40000002\
      00000003\
      40240000000000004024000000000000403E000000000000\
      403400000000000040340000000000004049000000000000\
      402400000000000040440000000000004034000000000000\
      00\
      40000002\
      00000002\
      404400000000000040440000000000004034000000000000\
      403E000000000000403E0000000000004049000000000000\
      """

      multi_line_string =
        MultiLineStringM.new([
          LineStringM.new([
            PointM.new(40.0, 40.0, 20.0),
            PointM.new(30.0, 30.0, 50.0)
          ]),
          LineStringM.new([
            PointM.new(10.0, 10.0, 30.0),
            PointM.new(20.0, 20.0, 50.0),
            PointM.new(10.0, 40.0, 20.0)
          ])
        ])

      assert MultiLineStringM.from_wkb(wkb, :hex) == {:ok, multi_line_string}
    end

    test "returns a MultiLineStringM from xdr-binary" do
      wkb = """
      00\
      40000005\
      00000002\
      00\
      40000002\
      00000003\
      40240000000000004024000000000000403E000000000000\
      403400000000000040340000000000004049000000000000\
      402400000000000040440000000000004034000000000000\
      00\
      40000002\
      00000002\
      404400000000000040440000000000004034000000000000\
      403E000000000000403E0000000000004049000000000000\
      """

      multi_line_string =
        MultiLineStringM.new([
          LineStringM.new([
            PointM.new(40.0, 40.0, 20.0),
            PointM.new(30.0, 30.0, 50.0)
          ]),
          LineStringM.new([
            PointM.new(10.0, 10.0, 30.0),
            PointM.new(20.0, 20.0, 50.0),
            PointM.new(10.0, 40.0, 20.0)
          ])
        ])

      assert wkb |> Hex.to_binary() |> MultiLineStringM.from_wkb() == {:ok, multi_line_string}
    end
  end

  describe "from_wkb!/2" do
    test "returns a MultiLineStringM from xdr-string" do
      wkb = """
      00\
      40000005\
      00000002\
      00\
      40000002\
      00000003\
      40240000000000004024000000000000403E000000000000\
      403400000000000040340000000000004049000000000000\
      402400000000000040440000000000004034000000000000\
      00\
      40000002\
      00000002\
      404400000000000040440000000000004034000000000000\
      403E000000000000403E0000000000004049000000000000\
      """

      multi_line_string =
        MultiLineStringM.new([
          LineStringM.new([
            PointM.new(40.0, 40.0, 20.0),
            PointM.new(30.0, 30.0, 50.0)
          ]),
          LineStringM.new([
            PointM.new(10.0, 10.0, 30.0),
            PointM.new(20.0, 20.0, 50.0),
            PointM.new(10.0, 40.0, 20.0)
          ])
        ])

      assert MultiLineStringM.from_wkb!(wkb, :hex) == multi_line_string
    end

    test "returns a MultiLineStringM from xdr-binary" do
      wkb = """
      00\
      40000005\
      00000002\
      00\
      40000002\
      00000003\
      40240000000000004024000000000000403E000000000000\
      403400000000000040340000000000004049000000000000\
      402400000000000040440000000000004034000000000000\
      00\
      40000002\
      00000002\
      404400000000000040440000000000004034000000000000\
      403E000000000000403E0000000000004049000000000000\
      """

      multi_line_string =
        MultiLineStringM.new([
          LineStringM.new([
            PointM.new(40.0, 40.0, 20.0),
            PointM.new(30.0, 30.0, 50.0)
          ]),
          LineStringM.new([
            PointM.new(10.0, 10.0, 30.0),
            PointM.new(20.0, 20.0, 50.0),
            PointM.new(10.0, 40.0, 20.0)
          ])
        ])

      assert wkb |> Hex.to_binary() |> MultiLineStringM.from_wkb!() == multi_line_string
    end

    test "raises an error for an invalid WKB string" do
      message = ~s(expected endian flag "00" or "01", got "no", at position 0)

      assert_raise Geometry.Error, message, fn ->
        MultiLineStringM.from_wkb!("nonono", :hex)
      end
    end

    test "raises an error for an invalid WKB binary" do
      message = "expected endian flag, at position 0"

      assert_raise Geometry.Error, message, fn ->
        MultiLineStringM.from_wkb!("nonono")
      end
    end
  end

  test "Enum.slice/3" do
    multi_line_string =
      MultiLineStringM.new([
        LineStringM.new([
          PointM.new(1, 2, 4),
          PointM.new(3, 4, 6)
        ]),
        LineStringM.new([
          PointM.new(1, 2, 4),
          PointM.new(11, 12, 14),
          PointM.new(13, 14, 16)
        ])
      ])

    assert [_line_string] = Enum.slice(multi_line_string, 1, 1)
  end
end
